### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kietil** [BrowserSync/recipes#35]
I have tried to run the html.injector example for a while now.. in the meantime, both npm and node has upgraded to new versions (in case that was the problem the first time), but even now, i get this long error that i got last time.

```
[BS] Serving files from: app
[BS] Watching files...
/Users/sivilll/code/pt/bs-recipes/recipes/html.injection/node_modules/bs-html-injector/index.js:220
        var valid = bs.io.of(bs.options.getIn(["socket", "namespace"])).sockets.map(function (client) {
                                                                                ^

TypeError: bs.io.of(...).sockets.map is not a function
    at requestNew (/Users/sivilll/code/pt/bs-recipes/recipes/html.injection/node_modules/bs-html-injector/index.js:220:81)
    at EventEmitter.fileChangedEvent (/Users/sivilll/code/pt/bs-recipes/recipes/html.injection/node_modules/bs-html-injector/index.js:190:9)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at AnonymousObserver._onNext (/Users/sivilll/code/pt/bs-recipes/recipes/html.injection/node_modules/browser-sync/lib/file-watcher.js:19:17)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/sivilll/code/pt/bs-recipes/recipes/html.injection/node_modules/rx/dist/rx.all.js:1828:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/sivilll/code/pt/bs-recipes/recipes/html.injection/node_modules/rx/dist/rx.all.js:1762:31)
    at Subject.onNext (/Users/sivilll/code/pt/bs-recipes/recipes/html.injection/node_modules/rx/dist/rx.all.js:11944:19)
    at FSWatcher.fn (/Users/sivilll/code/pt/bs-recipes/recipes/html.injection/node_modules/browser-sync/lib/file-watcher.js:37:21)
    at emitTwo (events.js:106:13)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! bs-recipes-html-injection@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bs-recipes-html-injection@1.0.0 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bs-recipes-html-injection package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bs-recipes-html-injection
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bs-recipes-html-injection
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sivilll/code/pt/bs-recipes/recipes/html.injection/npm-debug.log
```

Anyone know what this means? The terminal runs correctly when i enter "npm start" but on the very first change, this error occurs.

**Comment by sivilll** [comment]
Close this issue. I must have been drunk, when i issued it.
