### ISSUE TITLE
TypeError: bs.io.of(...).sockets.map is not a function

### ISSUE THREAD

**Issue by tony19** [BrowserSync/recipes#43]
The [html.injection](https://github.com/BrowserSync/recipes/tree/5ec13d0/recipes/html.injection) recipe failed after I edited `index.html` (I added `<h3>What's up?</h3>` after the `<p>`).

```shell
$ node app.js
[BS] [HTML Injector] Running...
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:3000
    External: http://192.168.10.101:3000
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.10.101:3001
 ---------------------------------------
[BS] Serving files from: app
[BS] Watching files...
/Users/tony/src/tmp/browser-sync-recipes/recipes/html.injection/node_modules/bs-html-injector/index.js:220
        var valid = bs.io.of(bs.options.getIn(["socket", "namespace"])).sockets.map(function (client) {
                                                                                ^

TypeError: bs.io.of(...).sockets.map is not a function
    at requestNew (/Users/tony/src/tmp/browser-sync-recipes/recipes/html.injection/node_modules/bs-html-injector/index.js:220:81)
    at EventEmitter.fileChangedEvent (/Users/tony/src/tmp/browser-sync-recipes/recipes/html.injection/node_modules/bs-html-injector/index.js:190:9)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at AnonymousObserver._onNext (/Users/tony/src/tmp/browser-sync-recipes/recipes/html.injection/node_modules/browser-sync/lib/file-watcher.js:19:17)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/tony/src/tmp/browser-sync-recipes/recipes/html.injection/node_modules/rx/dist/rx.js:1828:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/tony/src/tmp/browser-sync-recipes/recipes/html.injection/node_modules/rx/dist/rx.js:1762:31)
    at Subject.Rx.Subject.addProperties.onNext (/Users/tony/src/tmp/browser-sync-recipes/recipes/html.injection/node_modules/rx/dist/rx.js:5998:19)
    at FSWatcher.fn (/Users/tony/src/tmp/browser-sync-recipes/recipes/html.injection/node_modules/browser-sync/lib/file-watcher.js:37:21)
    at emitTwo (events.js:87:13)
```

### Environment
 * node 4.7.2
 * macOS Sierra 10.12

**Comment by tony19** [comment]
Commenting out that line (which assigns `valid`) and its reference seems to fix the issue (I actually see HTML injection working).

The lines I commented out in `node_modules/bs-html-injector/index.js`:
```javascript
    function requestNew (opts) {

        // Remove any
        // var valid = bs.io.of(bs.options.getIn(["socket", "namespace"])).sockets.map(function (client) {
        //     return client.handshake.headers.referer;
        // });

        logger.debug("Cache items: {yellow:%s", Object.keys(htmlInjector.cache).length);

        Object.keys(htmlInjector.cache).forEach(function (url) {

            // if (valid.indexOf(url) === -1) {
            //     delete htmlInjector.cache[url];
            //     return;
            // }
```

**Comment by tony19** [comment]
Looks like a duplicate of https://github.com/shakyShane/html-injector/issues/17
